{
    'name': 'Student Management',
    'version': '18.0.1.0.0',
    'category': 'Education',
    'summary': 'Manage students, classes, enrollments, attendance, exams, and timetable',
    'description': 'A comprehensive student management system for schools or institutions, now with attendance, exam, and timetable management.',
    'author': 'Kamal',
    'website': 'https://github.com/11kamal11/Student',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/student_action.xml',
        'views/student_views.xml',
        'views/enrollment_views.xml',
        'views/student_menu.xml',
        'views/class_views.xml',
        'views/course_views.xml',
        'views/attendance_views.xml',
        'views/exam_views.xml',
        'views/timetable_views.xml',
    ],
    'assets': {},
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
